spring.application.name=JwtAuth
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=jwtauth
#spring.mongodb.username=mohit
#spring.mongodb.password=mohit
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.security=DEBUG
jwt.secretkey=0943j8ft78rirfiumctu483oarei0r$^GUGT^&&FR$R&UHI(Y^*(YT*(HU*Y^$$#E#kceric93urcyn4qm94cmrifjed
